# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
###############
# pip updates (requirements files)
##############
  - package-ecosystem: "pip"
    directory: "/core/admin" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/docs" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/setup" # Location of package manifests
    schedule:
      interval: "weekly"

###############
# npm updates (package.json files)
##############
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/core/admin"
    schedule:
      interval: "weekly"

###############
# docker updates (Dockerfile files)
##############

  - package-ecosystem: "docker"
    directory: "/core/admin"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/core/dovecot"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/core/nginx"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/core/none"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/core/postfix"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/core/rspamd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/docs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/optional/clamav"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/optional/fetchmail"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/optional/radicale"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/optional/traefik-certdumper"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/optional/unbound"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/setup"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/webmails/rainloop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/webmails/roundcube"
    schedule:
      interval: "weekly"

###############
# github action updates (*.yml files)
##############
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github/workflows" # Location of package manifests
    schedule:
      interval: "monthly"

